name: 🚀 Laravel cPanel Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - staging
      - master

jobs:
  development-deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development'
    name: ⚙️ Development Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml

      - name: 📦 Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: 📦 Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: 🛠️ Check for Frontend
        id: check_frontend
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            echo "has_frontend=true" >> $GITHUB_OUTPUT
          else
            echo "has_frontend=false" >> $GITHUB_OUTPUT
          fi


      - name: 🚀 Deploy to Dev Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.DEV_FTP_HOST }}
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./
          server-dir: ./
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/.idea/**
            **/node_modules/**
            **/tests/**
            **/bootstrap/cache/**
            .env*
            docker-compose*
            vite.config.js
            webpack.mix.js
            package*.json
            composer.*
            phpunit.xml
            README.md
            .DS_Store
            Thumbs.db

      - name: 📢 Notify Slack (Dev Success)
        if: success() && contains(github.event.pull_request.title, 'slack')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Laravel Dev Bot 🧪'
          SLACK_ICON_EMOJI: ':test_tube:'
          SLACK_COLOR: '#439FE0'
          SLACK_TITLE: '✅ Dev Deployment Done'
          SLACK_MESSAGE: |
            🧪 *Development Deployment Completed*
            • Branch: development
            • PR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
            • Title: ${{ github.event.pull_request.title }}
            • By: ${{ github.event.pull_request.user.login }}

      - name: 📢 Notify Slack (Dev Failure)
        if: failure() && contains(github.event.pull_request.title, 'slack')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Laravel Dev Bot ❌'
          SLACK_ICON_EMOJI: ':x:'
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: '❌ Dev Deployment Failed'
          SLACK_MESSAGE: |
            🚨 *Development Deployment Failed*
            • Branch: development
            • PR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
            • Title: ${{ github.event.pull_request.title }}
            • By: ${{ github.event.pull_request.user.login }}

  staging-deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    name: 🚦 Staging Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml

      - name: 📦 Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: 📦 Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: 🛠️ Check for Frontend
        id: check_frontend
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            echo "has_frontend=true" >> $GITHUB_OUTPUT
          else
            echo "has_frontend=false" >> $GITHUB_OUTPUT
          fi


      - name: 🏗️ Build Assets (npm run build)
        if: steps.check_frontend.outputs.has_frontend == 'true'
        run: |
          npm ci --silent
          npm run build --silent

      - name: 🚀 Deploy to Staging Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.STAGING_FTP_HOST }}
          username: ${{ secrets.STAGING_FTP_USERNAME }}
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./
          server-dir: ./
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/.idea/**
            **/node_modules/**
            **/tests/**
            **/bootstrap/cache/**
            .env*
            docker-compose*
            vite.config.js
            webpack.mix.js
            package*.json
            composer.*
            phpunit.xml
            README.md
            .DS_Store
            Thumbs.db

      - name: 📢 Notify Slack (Staging Success)
        if: success() && contains(github.event.pull_request.title, 'slack')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Laravel Staging Bot 🚦'
          SLACK_ICON_EMOJI: ':traffic_light:'
          SLACK_COLOR: '#FFD700'
          SLACK_TITLE: '✅ Staging Deployment Done'
          SLACK_MESSAGE: |
            🚦 *Staging Deployment Completed*
            • Branch: staging
            • PR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
            • Title: ${{ github.event.pull_request.title }}
            • By: ${{ github.event.pull_request.user.login }}

      - name: 📢 Notify Slack (Staging Failure)
        if: failure() && contains(github.event.pull_request.title, 'slack')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Laravel Staging Bot ❌'
          SLACK_ICON_EMOJI: ':x:'
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: '❌ Staging Deployment Failed'
          SLACK_MESSAGE: |
            🚨 *Staging Deployment Failed*
            • Branch: staging
            • PR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
            • Title: ${{ github.event.pull_request.title }}
            • By: ${{ github.event.pull_request.user.login }}

  production-deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    name: 🛡️ Production Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml

      - name: 📦 Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: 📦 Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: 🛠️ Check for Frontend
        id: check_frontend
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            echo "has_frontend=true" >> $GITHUB_OUTPUT
          else
            echo "has_frontend=false" >> $GITHUB_OUTPUT
          fi


      - name: 🏗️ Build Assets (npm run build)
        if: steps.check_frontend.outputs.has_frontend == 'true'
        run: |
          npm ci --silent
          npm run build --silent

      - name: 🚀 Deploy to Production Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PROD_FTP_HOST }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./
          server-dir: ./
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/.idea/**
            **/node_modules/**
            **/tests/**
            **/bootstrap/cache/**
            .env*
            docker-compose*
            vite.config.js
            webpack.mix.js
            package*.json
            composer.*
            phpunit.xml
            README.md
            .DS_Store
            Thumbs.db

      - name: 📢 Notify Slack (Production Success)
        if: success() && contains(github.event.pull_request.title, 'slack')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Laravel Deployer 🚀'
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_COLOR: '#36a64f'
          SLACK_TITLE: '✅ Production Deployed'
          SLACK_MESSAGE: |
            🎉 *Production Deployment Completed*
            • Branch: master
            • PR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
            • Title: ${{ github.event.pull_request.title }}
            • By: ${{ github.event.pull_request.user.login }}

      - name: 📢 Notify Slack (Production Failure)
        if: failure() && contains(github.event.pull_request.title, 'slack')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'Laravel Deployer ❌'
          SLACK_ICON_EMOJI: ':x:'
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: '❌ Production Deployment Failed'
          SLACK_MESSAGE: |
            🚨 *Production Deployment Failed*
            • Branch: master
            • PR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
            • Title: ${{ github.event.pull_request.title }}
            • By: ${{ github.event.pull_request.user.login }}
